[2024-10-07T03:18:09.174+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-07T03:18:09.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [queued]>
[2024-10-07T03:18:09.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [queued]>
[2024-10-07T03:18:09.190+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-10-07T03:18:09.198+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-06 01:00:00+00:00
[2024-10-07T03:18:09.201+0000] {standard_task_runner.py:64} INFO - Started process 4121 to run task
[2024-10-07T03:18:09.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_random_forest', 'train_model', 'scheduled__2024-10-06T01:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/HW1.py', '--cfg-path', '/tmp/tmpkzyt2e5y']
[2024-10-07T03:18:09.205+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask train_model
[2024-10-07T03:18:09.232+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_random_forest.train_model scheduled__2024-10-06T01:00:00+00:00 [running]> on host 22775caa7dfb
[2024-10-07T03:18:09.278+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_random_forest' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T01:00:00+00:00'
[2024-10-07T03:18:09.278+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-07T03:18:09.294+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-1 with path random_forest/datasets/prepared_data.csv
[2024-10-07T03:18:09.302+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-07T03:18:09.302+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-07T03:18:26.790+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-07T03:18:26.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/HW1.py", line 111, in train_model
    s3_hook.load_bytes(pickle.dumps(model), key=model_path, bucket_name=BUCKET, replace=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1205, in load_bytes
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1255, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 348, in _main
    response = client.create_multipart_upload(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestTimeTooSkewed) when calling the CreateMultipartUpload operation: The difference between the request time and the current time is too large.
[2024-10-07T03:18:26.806+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Nikita_Lapshin_random_forest, task_id=train_model, run_id=scheduled__2024-10-06T01:00:00+00:00, execution_date=20241006T010000, start_date=20241007T031809, end_date=20241007T031826
[2024-10-07T03:18:26.821+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task train_model (An error occurred (RequestTimeTooSkewed) when calling the CreateMultipartUpload operation: The difference between the request time and the current time is too large.; 4121)
[2024-10-07T03:18:26.887+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-07T03:18:26.913+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T03:18:26.915+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
